services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
